name = "story_bakery/value_by_priority"
version = "0.1.0"
license = "MIT"
includes = [
    "pesde.toml",
    "LICENSE",
    "README.md",
    ".pesde/scripts/roblox_sync_config_generator.luau",
    ".pesde/scripts/sourcemap_generator.luau",
    "src/**/*.luau",
    "src/**/*.json",
    "tests/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
BufferBuilder = { repo = "https://github.com/StoryBakery/BufferBuilder", rev = "main" }
BufferReader = { repo = "https://github.com/StoryBakery/BufferReader", rev = "main" }
ReplicatedInstanceId = { repo = "https://github.com/StoryBakery/ReplicatedInstanceId", rev = "main" }
TableUtil = { repo = "https://github.com/StoryBakery/TableUtil", rev = "main" }
Signal = { repo = "https://github.com/StoryBakery/Signal", rev = "main" }
Maid = { repo = "https://github.com/StoryBakery/Maid", rev = "main" }
LinearInterpolation = { repo = "https://github.com/StoryBakery/LinearInterpolation", rev = "main" }
TypeInfos = { repo = "https://github.com/StoryBakery/TypeInfos", rev = "main" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
